---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: document
  path: exampleSite/content/about/_index.md
  label: About
  match: "**/*"
- type: heading
  label: Blog Post
- type: directory
  path: exampleSite/content/blog
  label: Post
  create: documents
  match: "**/*"
  templates:
  - post
- type: heading
  label: Writing
- type: directory
  path: exampleSite/content/writing
  label: Writing
  create: documents
  match: "**/*"
  templates:
  - writing
- type: heading
  label: Author
- type: heading
  label: Configuration
- type: directory
  path: exampleSite
  label: Configuration
  create: all
  match: "*.toml"
  new_doc_ext: toml
- type: directory
  path: exampleSite/data
  label: Homepage
  create: all
  match: "**/*"
upload_dir: exampleSite/static/images/writing
public_path: "/images/writing"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.58.2
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public
version: 0.58.2
